"""
LightGBM Classification Module
==============================

This module implements the LightGBM-based binary intrusion
classification stage described in:

Section 3.6 - Proposed Methodology
Section 4.1.1 - Hyperparameter Configuration

The classifier operates on contextualized feature embeddings
generated by the TabTransformer representation learning module.

Learning Objective:
Binary Classification (Benign vs Attack)
"""

import lightgbm as lgb

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


# ============================================================
# LightGBM Hyperparameter Configuration
# ============================================================

NUM_LEAVES = 64
MAX_DEPTH = -1

LEARNING_RATE = 0.05
N_ESTIMATORS = 500

FEATURE_FRACTION = 0.8
BAGGING_FRACTION = 0.8
BAGGING_FREQ = 5

MIN_DATA_IN_LEAF = 20

LAMBDA_L2 = 0.1

RANDOM_STATE = 42


# ============================================================
# Build LightGBM Classifier
# ============================================================

def build_lightgbm_classifier():
    """
    Initialize LightGBM classifier using manuscript-aligned
    hyperparameter configuration.
    """

    classifier = lgb.LGBMClassifier(

        objective="binary",

        num_leaves=NUM_LEAVES,

        max_depth=MAX_DEPTH,

        learning_rate=LEARNING_RATE,

        n_estimators=N_ESTIMATORS,

        feature_fraction=FEATURE_FRACTION,

        bagging_fraction=BAGGING_FRACTION,

        bagging_freq=BAGGING_FREQ,

        min_child_samples=MIN_DATA_IN_LEAF,

        reg_lambda=LAMBDA_L2,

        class_weight="balanced",

        random_state=RANDOM_STATE
    )

    return classifier


# ============================================================
# Train Classifier
# ============================================================

def train_lightgbm_classifier(
    X_train_embeddings,
    y_train
):
    """
    Train LightGBM classifier on contextual feature embeddings.
    """

    classifier = build_lightgbm_classifier()

    classifier.fit(
        X_train_embeddings,
        y_train
    )

    return classifier


# ============================================================
# Model Evaluation
# ============================================================

def evaluate_model(
    classifier,
    X_test_embeddings,
    y_test
):
    """
    Evaluate binary intrusion detection performance.
    """

    predictions = classifier.predict(
        X_test_embeddings
    )

    prediction_probabilities = classifier.predict_proba(
        X_test_embeddings
    )[:, 1]

    results = {

        "Accuracy": accuracy_score(
            y_test,
            predictions
        ),

        "Precision": precision_score(
            y_test,
            predictions
        ),

        "Recall": recall_score(
            y_test,
            predictions
        ),

        "F1-Score": f1_score(
            y_test,
            predictions
        ),

        "AUC-ROC": roc_auc_score(
            y_test,
            prediction_probabilities
        )
    }

    return results


# ============================================================
# Main Execution
# ============================================================

if __name__ == "__main__":

    print(
        "LightGBM Binary Classification Module Initialized."
    )
